m1=int(input("Enter marks of 1st subject:"))
m2=int(input("Enter marks of 2nd subject:"))
m3=int(input("Enter marks of 3rd subject:"))
m4=int(input("Enter marks of 4th subject:"))
m5=int(input("Enter marks of 5th subject:"))
m6=int(input("Enter marks of 6th subject:"))
print("Average=",(m1+m2+m3+m4+m5+m6)/6)
